version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6npoi8ij1fmi"
s3_prefix = "sam-app"
region = "eu-west-1"
profile = "xpeppers-test"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MyAccountB=\"831650818513\""
