version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo start build
      - sam build
      - echo start deploy
      - sam deploy --s3-bucket $S3Bucket --stack-name $APP_NAME --capabilities CAPABILITY_IAM

artifacts:
  type: zip
  files:
    - package.yaml